version: '3'

services:

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticket_booking_db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  mock-payment-api:
    image: "wiremock/wiremock:3.5.2"
    ports:
      - "8000:8000"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--port=8000" ]

  application:
    image: "${REPOSITORY_URI}:${IMAGE_TAG}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - mock-payment-api
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_SCHEMA: "${DB_SCHEMA}"
      DB_USERNAME: "${DB_USER}"
      DB_PASSWORD: "${DB_PASS}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      PAYMENT_API_HOST: "${PAYMENT_API_HOST}"
      PAYMENT_API_PORT: "${PAYMENT_API_PORT}"