spring:
  application:
    name: rbt-ticket-booking
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_booking_db?rewriteBatchedInserts=true
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: rbt
        order_inserts: true
        jdbc:
          batch_size: 100
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: rbt
    default-schema: rbt
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: booking-service
      auto-offset-reset: earliest
      max-poll-records: 50
    producer:
      acks: all
      retries: 5
      properties:
        linger:
          ms: 50
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes.enabled: true
      show-details: always
  health:
    db:
      enabled: true

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: UQv2bDg0Y2rX7oQe5fV9hJ3kLmNz1Pa4Rb8Sc6Td0UvWxYz2A3B5C7D9E1F3G5H7
    issuer: rbt-ticket-booking
    expiration-min: 60
  dummy-json:
    base-url: https://dummyjson.com
  payment-api:
    base-url: http://localhost:8000
  admin-users:
    - emilys
    - michaelw
    - sophiab
  ticket-ttl-min: 10