CREATE SCHEMA IF NOT EXISTS rbt;
SET search_path TO rbt, public;

-- Venue
CREATE TABLE venue (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name TEXT NOT NULL,
                       address TEXT,
                       capacity INT NOT NULL CHECK (capacity > 0),
                       created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Performer
CREATE TABLE performer (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name TEXT NOT NULL,
                           genre TEXT,
                           created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                           updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Event
CREATE TABLE event (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       venue_id BIGINT NOT NULL REFERENCES venue(id),
                       performer_id BIGINT REFERENCES performer(id),
                       name TEXT NOT NULL,
                       description TEXT,
                       start_time TIMESTAMPTZ NOT NULL,
                       total_tickets INT NOT NULL CHECK (total_tickets >= 0),
                       max_per_request INT NOT NULL CHECK (max_per_request > 0),
                       status VARCHAR(16) NOT NULL,
                       created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Ticket
CREATE SEQUENCE IF NOT EXISTS ticket_seq START WITH 1 INCREMENT BY 100;

CREATE TABLE ticket (
                        id BIGINT PRIMARY KEY DEFAULT nextval('ticket_seq'),
                        event_id BIGINT NOT NULL REFERENCES event(id),
                        price NUMERIC(12,2),
                        status VARCHAR(16) NOT NULL,
                        booked_at TIMESTAMPTZ,
                        booked_by_ref VARCHAR(128),
                        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
